70321_1_Lankevich/Controllers/BookController.cs
using _70321_1_Lankevich.DAL.Entities;
using _70321_1_Lankevich.DAL.Interfaces;
using _70321_1_Lankevich.Models;
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace _70321_1_Lankevich.Controllers
{
    public class BookController : Controller
    {
        IRepository<Book> repository;
        int pageSize = 3;
        public BookController(IRepository<Book> repo)
        {
            repository = repo;
        }
        // GET: Book
        public ActionResult List(string genre, int page=1)
        {
            var lst = repository.GetAll()
                                .Where(d => genre == null
                                || d.GenreName.Equals(genre))
                                .OrderBy(d => d.Price);
            var model = PageListViewModel<Book>.CreatePage(lst, page, pageSize);
            if (Request.IsAjaxRequest())
            {
                return PartialView("ListPartial", model);
            }
            return View(PageListViewModel<Book>.CreatePage(lst, page, pageSize));
        }

        public FileContentResult GetImage(int id)
        {
            var book = repository.Get(id);
            if (book != null)
            {
                return new FileContentResult(book.Image, book.MimeType);
            }
            else return null;
        }

        public async Task<FileResult> GetImageAsync(int id)
        {
            var book = await repository.GetAsync(id);
            if (book != null)
            {
                return new FileContentResult(book.Image, book.MimeType);
            }
            else return null;
        }
    }
}

70321_1_Lankevich/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _70321_1_Lankevich.DAL.Entities;
using _70321_1_Lankevich.DAL.Interfaces;
using _70321_1_Lankevich.Models;

namespace _70321_1_Lankevich.Controllers
{
    public class CartController : Controller
    {
        IRepository<Book> repository;

        public CartController(IRepository<Book> repo)
        {
            repository = repo;
        }

        [Authorize]
        // GET: Cart
        public ActionResult Index(string returnUrl, Cart cart)
        {
            TempData["returnUrl"] = returnUrl;
            //return View(GetCart());
            return View(cart);
        }

        /// <summary>
        /// Получение корзины из сессии
        /// </summary>
        /// <returns></returns>
        public Cart GetCart()
        {
            Cart cart = Session["cart"] as Cart;
            if (cart == null)
            {
                cart = new Cart();
                Session["cart"] = cart;
            }
            return cart;
        }

        public RedirectResult AddToCart(int id, string returnUrl)
        {
            var item = repository.Get(id);
            if (item != null)
            {
                GetCart().AddItem(item);
                TempData["MessageCart"] = string.Format("Успешно добавлен элемент: {0}", item.Name);
            }
            else
            {
                TempData["MessageCart"] = "Элемент не был добавлен";
            }

            return Redirect(returnUrl);

        }

        public PartialViewResult CartSummary(string returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return PartialView(GetCart());
        }

        [HttpPost]
        public JsonResult DeleteFromCart(int id)
        {
            Book book = repository.Get(id);

            if (book != null)
            {
                Cart cart = GetCart();
                cart.RemoteItem(book);

                //ViewBag.MessageCart = string.Format("Успешно удален элемент: {0}", book.Name);

                var r = new { result = true, cartId = id, quantity = cart.CountItem(id), avarege = cart.GetAvarege(), message = string.Format("Успешно удален элемент: {0}", book.Name) };
                return Json(r);
            }

            return Json(new { result = false, message = "Элемент не был удален" });
        }
    }
}

70321_1_Lankevich/Controllers/MenuController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using _70321_1_Lankevich.Models;
using _70321_1_Lankevich.DAL.Entities;
using _70321_1_Lankevich.DAL.Interfaces;

namespace _70321_1_Lankevich.Controllers
{
    public class MenuController : Controller
    {
        List<MenuItem> items;
        IRepository<Book> repository;
        public MenuController(IRepository<Book> repo)
        {
            repository = repo;

            items = new List<MenuItem>
            {
                new MenuItem{Name="Домой", Controller="Home", Action="Index", Active=string.Empty},
                new MenuItem{Name="Каталог Книг", Controller="Book", Action="List", Active=string.Empty},
                new MenuItem{Name="Администрирование", Controller="Admin", Action="Index", Active=string.Empty}
            };
        }

        /*
            Методы «Main», «UserInfo», «Side» и «Map» должны возвращать частичные представления главного меню, 
            меню пользователя (регистрация и вход), меню в левой колонке и карту сайта соответственно.  Вызов 
            частичных представлений осуществлять с помощью расширяющего метода @Html.Action, так как частичное 
            представление возвращается методом контроллера. 
         */
        [ChildActionOnly]
        public PartialViewResult Main(string a = "Index", string c = "Home")
        {
            items.First(m => m.Controller == c)
                .Active = "active";
            return PartialView(items);
        }

        [ChildActionOnly]
        public PartialViewResult UserInfo()
        {

            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult Side()
        {
            var genres = repository
                        .GetAll()
                        .Select(d => d.GenreName)
                        .Distinct();
            return PartialView(genres);
        }

        [ChildActionOnly]
        public PartialViewResult Map()
        {
            return PartialView(items);
        }

        
    }
}

70321_1_Lankevich/Views/Shared/ItemViewPartial.cshtml
@model _70321_1_Lankevich.DAL.Entities.Book

<div class='col-md-4'>
    <div class="thumbnail">
        <img height="200" src="@Url.Action("GetImageAsync", "Book", new { id=Model.Id})" alt="NoImage" />
        <div class="caption">
            <div class="item-name">
                <h3>@Model.Name</h3>
            </div>
            <div class="item-description">
                @Model.Description
            </div>
            <div class="centered">
                <h3 class="badge">Цена @Model.Price</h3>
            </div>
            <div class="centered">
                <a href="@Url.Action("AddToCart", "Cart", new { id = Model.Id, returnUrl = Request.Path})"
                   class="btn btn-primary">
                    <span class="glyphicon glyphicon-shopping-cart"></span>В корзину
                </a>
            </div>
        </div>
    </div>
</div>

70321_1_Lankevich/Views/Shared/PagerPartial.cshtml
@model _70321_1_Lankevich.Models.PageListViewModel<_70321_1_Lankevich.DAL.Entities.Book>
@using System.Text;

@{
    var genreName = Request.RequestContext.RouteData.Values["genre"];
}

@{
    var result = new StringBuilder();

    // стрелка влево
    var liPrevNext = new TagBuilder("li");
    //liPrevNext.InnerHtml = Html.ActionLink("<<", "List", new { genre = genreName, page = Model.CurrentPage - 1 }).ToString();
    liPrevNext.InnerHtml = Ajax.ActionLink("<<", "List", new { genre = genreName, page = Model.CurrentPage - 1 },
                                         new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "List" }).ToString();
    if (Model.CurrentPage == 1)
    {
        liPrevNext.AddCssClass("disabled");
    }

    result.Append(liPrevNext.ToString());

    //пейджер
    for (int i = 1; i <= Model.TotalPages; i++)
    {
        var li = new TagBuilder("li");
        if (i == Model.CurrentPage)
        {
            li.AddCssClass("active");
        }
        //var a = new TagBuilder("a");
        //a.MergeAttribute("href", Url.Action("List", new {genre = genreName, page = i }));
        //a.InnerHtml = i.ToString();
        //li.InnerHtml = a.ToString();
        li.InnerHtml = Ajax.RouteLink(i.ToString(), new { action = "List", genre = genreName, page = i },
                                    new AjaxOptions { UpdateTargetId = "List", InsertionMode = InsertionMode.Replace }).ToString();
        result.Append(li.ToString());
    }

    //стрелка вправо
    liPrevNext = new TagBuilder("li");

    //liPrevNext.InnerHtml = Html.ActionLink(">>", "List", new { genre = genreName, page = Model.CurrentPage + 1 }).ToString();
    liPrevNext.InnerHtml = Ajax.ActionLink(">>", "List", new { genre = genreName, page = Model.CurrentPage - 1 },
                                         new AjaxOptions { UpdateTargetId = "List", InsertionMode = InsertionMode.Replace }).ToString();
    if (Model.CurrentPage == Model.TotalPages)
    {
        liPrevNext.AddCssClass("disabled");
    }
    result.Append(liPrevNext.ToString());


}

<ul class="pagination">
    @MvcHtmlString.Create(result.ToString())
</ul>

70321_1_Lankevich/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    @*<link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/MySite.css" rel="stylesheet" />*@
    @Styles.Render("~/bundles/styles")
    @RenderSection("Styles", required: false)
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div class="header-strip">
            <div class="container">

                @Html.Action("UserInfo", "Menu")
            </div>
            <div class="container">
                <div class="navbar navbar-inverse" role="navigation">
                    <div class="logo">
                        <a class="navbar-brand" href="index.html">Ланкевич Евгений</a>
                    </div>
                    @* Здесь с помощью метода Request.RequestContext.RouteData.Values извлекаются параметры
                        из текущего маршрута, чтобы передать их вместе с запросом контроллеру Menu.  *@
                @Html.Action("Main", "Menu", new { c = Request.RequestContext.RouteData.Values["controller"] })
            </div>
        </div>
    </div>
    <div class="main-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-3">
                    <h2>@ViewBag.MyText</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    @RenderSection("SidePanel", required: false) 
                </div>
                <div class="col-md-9">
                    @RenderBody() @*Вспомогательный метод для взаимодействия с представлением.*@ 
                </div>
            </div>
        </div>
    </div>
    <div class="footer-strip">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    @Html.Action("Map", "Menu")
                </div>
                <div class="col-md-3 col-md-offset-6">
                    <h6>Социальные сети</h6>
                    <a href="https://www.linkedin.com/" class="social-icon in"></a>
                    <a href="http://twitter.com" class="social-icon twitter"></a>
                    <a href="http://facebook.com" class="social-icon facebook"></a>
                </div>
            </div>
        </div>
    </div>
    @*<script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>*@
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("Scripts", false)

</body>
</html>